
<?php $this->headTitle('Blog'); ?>

<h1>Blog</h1>
<p>
    <a href="<?=$this->url('post', ['action' => 'add']);?>">
        new Post
    </a>
</p>
<table class="table">
    <tr>
        <th>Title</th>
        <th>Action</th>
    </tr>

    <?php foreach ($posts as $post): ?>
    <tr>
        <td><?=$this->escapeHtml($post->title);?></td>
        <td>
            <a href="<?=$this->url('post', ['action' => 'edit', 'id' => $post->id]); ?>" class="btn btn-success">
                Edit
            </a>

            <a href="<?=$this->url('post', ['action' => 'delete', 'id' =>  $post->id]); ?>" class="btn btn-danger">
                Delete
            </a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>